// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIBADP_zih3Eid6aHmYqkdNuUpt2Ak6w',
    appId: '1:267301766941:web:f9fec1ce1149996df9c3f4',
    messagingSenderId: '267301766941',
    projectId: 'employee-diary-292b2',
    authDomain: 'employee-diary-292b2.firebaseapp.com',
    storageBucket: 'employee-diary-292b2.firebasestorage.app',
    measurementId: 'G-37LMZK7EEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCeGENEath4n0QI7ve-hjAVHjzLuyJlH4',
    appId: '1:267301766941:android:37f8b894fdf54f88f9c3f4',
    messagingSenderId: '267301766941',
    projectId: 'employee-diary-292b2',
    storageBucket: 'employee-diary-292b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCviOUMNTGiJZXknSYttRnIoTEqTeIURZI',
    appId: '1:267301766941:ios:1a8e083023a6410af9c3f4',
    messagingSenderId: '267301766941',
    projectId: 'employee-diary-292b2',
    storageBucket: 'employee-diary-292b2.firebasestorage.app',
    iosBundleId: 'com.example.employeeDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCviOUMNTGiJZXknSYttRnIoTEqTeIURZI',
    appId: '1:267301766941:ios:1a8e083023a6410af9c3f4',
    messagingSenderId: '267301766941',
    projectId: 'employee-diary-292b2',
    storageBucket: 'employee-diary-292b2.firebasestorage.app',
    iosBundleId: 'com.example.employeeDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNIBADP_zih3Eid6aHmYqkdNuUpt2Ak6w',
    appId: '1:267301766941:web:384b74f991b8ec54f9c3f4',
    messagingSenderId: '267301766941',
    projectId: 'employee-diary-292b2',
    authDomain: 'employee-diary-292b2.firebaseapp.com',
    storageBucket: 'employee-diary-292b2.firebasestorage.app',
    measurementId: 'G-HZMXVBEH4K',
  );
}
